export const metadata = {
  title: "Terms of service",
};

function page() {
  return (
    <div className="mx-auto mb-10 mt-6 max-w-[1200px] border-b border-primary-700 bg-primary-800 px-5 pb-16 text-primary-100 lg:mb-16 lg:mt-14">
      <h1 className="mb-3 text-5xl font-bold lg:mb-14 xl:text-7xl">
        Terms of Use for Amuse
      </h1>

      <strong className="mb-4 inline-block">Last Updated: 18 March 2024</strong>
      <p className="mb-4 font-medium">
        Welcome to Amuse, provided by AVA Consulting Pty Ltd. By accessing or
        using our app, you agree to be bound by these Terms of Use
        (&quot;Terms&quot;). If you do not agree to these Terms, please do not
        use the Amuse app.
      </p>

      <h2 className="mb-2 bg-secondary-heading-gradient bg-clip-text text-3xl font-bold text-transparent lg:mb-5 xl:text-5xl">
        Plus Subscription
      </h2>
      <h3 className="mb-4 text-lg font-bold">Subscription Details</h3>
      <ul className="mb-2 flex list-disc flex-col gap-1 pl-8 lg:mb-5">
        <li>
          <strong>Plan Name:</strong>
          <span>Plus Plan:</span>
        </li>
        <li>
          <strong>Benefits:</strong>
          <ul className="flex list-disc flex-col gap-1 pl-8">
            <li>Access all completed topics anytime through Topic Archives.</li>
            <li>
              Daily Review: Receive 5 cards a day to keep past lessons fresh.
            </li>
            <li>
              Advanced AI: Enjoy more personalized and effective learning cards.
            </li>
            <li>Exclusive access to Popular Topics.</li>
          </ul>
        </li>
        <li>
          <strong>Trial Period:</strong>
          <span>
            1 month of full access for new users only, after which the
            subscription automatically renews.
          </span>
        </li>
        <li>
          <strong>Payment:</strong>
          <span>Managed through Apple App Store or Google Play Store.</span>
        </li>
        <li>
          <strong>Renewal:</strong>
          <span>
            Subscriptions renew automatically unless cancelled by the user
            through the app store settings.
          </span>
        </li>
      </ul>
      <h3 className="mb-4 text-lg font-bold">Cancellation and Refund</h3>
      <p className="mb-4 font-medium">
        Users can cancel their subscription at any time through the app store
        settings. No refunds are provided for cancelled subscriptions.
        Cancellations take effect at the end of the current billing cycle. Users
        wishing to avoid renewal charges must cancel their subscription before
        the renewal date.
      </p>
      <h2 className="mb-2 bg-secondary-heading-gradient bg-clip-text text-3xl font-bold text-transparent lg:lg:mb-5 xl:text-5xl">
        Use of the App
      </h2>
      <h3 className="mb-4 text-lg font-bold">Intellectual Property</h3>
      <p className="mb-4 font-medium">
        All content provided within the Amuse app, including text, graphics,
        logos, and software, is owned by AVA Consulting Pty Ltd. Users are
        permitted to share and publish content from the app, provided it is not
        done for commercial purposes.
      </p>
      <h3 className="mb-4 text-lg font-bold">
        Disclaimers and Limitation of Liability
      </h3>
      <p className="mb-4 font-medium">
        Content generated by the app is provided &quot;as is,&quot; and while we
        strive for accuracy, AVA Consulting Pty Ltd does not guarantee the
        correctness of the content. We are not liable for any misinformation or
        errors produced by the app.
      </p>
      <h2 className="mb-2 bg-secondary-heading-gradient bg-clip-text text-3xl font-bold text-transparent lg:mb-5 xl:text-5xl">
        Governing Law and Dispute Resolution
      </h2>
      <p className="mb-4 font-medium">
        This Agreement shall be governed by the laws of NSW, Australia, without
        regard to its conflict of law provisions. Any disputes arising from or
        related to the use of the Amuse app shall be subject to the exclusive
        jurisdiction of the courts of NSW, Australia.
      </p>
      <h2 className="mb-2 bg-secondary-heading-gradient bg-clip-text text-3xl font-bold text-transparent lg:mb-5 xl:text-5xl">
        Amendments and Contact Information
      </h2>
      <ul className="mb-2 flex list-disc flex-col gap-1 pl-8 lg:mb-5">
        <li>
          <strong>Amendments:</strong>
          <span>
            We reserve the right to modify these Terms at any time. Changes will
            be posted on this page with an updated revision date.
          </span>
        </li>
        <li>
          <strong>Contact:</strong>
          <span>
            For inquiries or complaints regarding these Terms, please contact us
            via the methods provided in our Privacy Policy.
          </span>
        </li>
      </ul>
      <p className="mb-4 font-medium">
        By using Amuse, you acknowledge that you have read, understood, and
        agreed to these Terms.
      </p>
    </div>
  );
}

export default page;
